import os
import pynput
import time
from pynput.keyboard import Key, Controller
episode_script = [
    "All", "right,", "ladies", "and", "gentleman,",
    "this", "is", "the", "moment", "we've", "been", "waiting", "for.",
    "The", "presenta--",
    "Daniel", "LaRusso's", "gonna", "fight?",
    "Daniel", "LaRusso's", "gonna", "fight!",
    "Now,", "isn't", "this", "what", "it's", "all", "about,", "folks?",
    "Go!",
    "Hiyah!",
    "-Fight!",
    "-Here", "we", "go.",
    "Turn.", "Kneel.",
    "Johnny,", "you're", "a", "cream", "puff!",
    "Sweep", "the", "leg.",
    "You", "have", "a", "problem", "with", "that?",
    "No,", "Sensei.",
    "No", "mercy.",
    "Two", "points,", "LaRusso.", "Lawrence,", "nothing.",
    "Ready?", "Fight.",
    "One", "point,", "Lawrence.",
    "One", "point,", "Lawrence.", "Two,", "two.",
    "Hiyah!",
    "Get", "him", "a", "body", "bag!", "Yeah!",
    "Warning", "for", "illegal", "contact", "to", "the", "knee.",
    "Whoever", "wins", "the", "next", "point", "will", "be", "our", "new", "champion.",
    "Finish", "him!",
    "Daniel", "LaRusso!",
    "Ugh.",
    "Hey,", "I'm", "Miguel.",
    "My", "family", "and", "I", "just", "moved", "into", "109.",
    "Great.", "More", "immigrants.",
    "Actually,", "we're", "from", "Riverside.",
    "But", "anyways,", "I", "was", "just", "wondering", "if", "you", "were",
    "having", "trouble", "with", "your", "water", "pressure,",
    "'cause", "I", "know", "our", "sink's", "being", "a", "little", "weird", "right", "now", "and--",
    "Oh,", "bottles", "go", "in", "the", "blue", "bin.",
    "Listen,", "Menudo...",
    "I've", "lived", "in", "this", "sh*thole", "for", "over", "ten", "years.",
    "The", "pipe's", "don't", "work.", "The", "fountain's", "full", "of", "piss.",]
bee_script = [
    'According to all known laws of aviation',
    'there is no way a bee',
    'should be able to fly.',
    'Its wings are too small to get',
    'its fat little body off the ground.',
    'The bee, of course, flies anyway',
    'because bees dont care',
    'what humans think is impossible.',
    'Yellow, black. Yellow, black.',
    'Yellow, black. Yellow, black.',
    'Ooh, black and yellow!',
    'Lets shake it up a little.',
    'Barry! Breakfast is ready!',
    'Ooming!',
    'Hang on a second.',
    'Hello?',
    '- Barry?',
    '- Adam?',
    '- Oan you believe this is happening?',
    '- I cant. Ill pick you up.',
    'Looking sharp.',
    'Use the stairs. Your father',
    'paid good money for those.',
    'Sorry. Im excited.',
    'Heres the graduate.',
    'Were very proud of you, son.',
    'A perfect report card, all Bs.',
    'Very proud.',
    'Ma! I got a thing going here.',
    '- You got lint on your fuzz.',
    '- Ow! Thats me!',
    '- Wave to us! Well be in row 118,000.',
    '- Bye!',
    'Barry, I told you,',
    'stop flying in the house!',
    '- Hey, Adam.',
    '- Hey, Barry.',
    '- Is that fuzz gel?',
    '- A little. Special day, graduation.',
    'Never thought Id make it.',
    'Three days grade school,',
    'three days high school.',
    'Those were awkward.',
    'Three days college. Im glad I took',
    'a day and hitchhiked around the hive.',
    'You did come back different.',
    '- Hi, Barry.',
    '- Artie, growing a mustache? Looks good.',
    '- Hear about Frankie?',
    '- Yeah.',
    '- You going to the funeral?',
    '- No, Im not going.',
    'Everybody knows,',
    'sting someone, you die.',
    'Dont waste it on a squirrel.',
    'Such a hothead.',
    'I guess he could have',
    'just gotten out of the way.',
    'I love this incorporating',
    'an amusement park into our day.',
    'Thats why we dont need vacations.',
    'Boy, quite a bit of pomp...',
    'under the circumstances.',
    '- Well, Adam, today we are men.',
    '- We are!',
    '- Bee-men.',
    '- Amen!',
    'Hallelujah!',
    'Students, faculty, distinguished bees,',
    'please welcome Dean Buzzwell.',
    'Welcome, New Hive Oity',
    'graduating class of...',
    '...9:15.',
    'That concludes our ceremonies.',
    'And begins your career',
    'at Honex Industries!',
    'Will we pick ourjob today?',
    'I heard its just orientation.',
    'Heads up! Here we go.',
    'Keep your hands and antennas',
    'inside the tram at all times.',
    '- Wonder what itll be like?',
    '- A little scary.',
    'Welcome to Honex,',
    'a division of Honesco',
    'and a part of the Hexagon Group.',
    'This is it!',
    'Wow.',
    'Wow.',
    'We know that you, as a bee,',
    'have worked your whole life',
    'to get to the point where you',
    'can work for your whole life.',
    'Honey begins when our valiant Pollen',
    'Jocks bring the nectar to the hive.',
    'Our top-secret formula',
    'is automatically color-corrected,',
    'scent-adjusted and bubble-contoured',
    'into this soothing sweet syrup',
    'with its distinctive',
    'golden glow you know as...',
    'Honey!',
    '- That girl was hot.',
    '- Shes my cousin!',
    '- She is?',
    '- Yes, were all cousins.',
    '- Right. Youre right.',
    '- At Honex, we constantly strive',
    'to improve every aspect',
    'of bee existence.',
    'These bees are stress-testing',
    'a new helmet technology.',
    '- What do you think he makes?',
    '- Not enough.',
    'Here we have our latest advancement,',
    'the Krelman.',
    '- What does that do?',
    '- Oatches that little strand of honey',
    'that hangs after you pour it.',
    'Saves us millions.',
    'Oan anyone work on the Krelman?',
    'Of course. Most bee jobs are',
    'small ones. But bees know',
    'that every small job,',
    'if its done well, means a lot.',
    'But choose carefully',
    'because youll stay in the job',
    'you pick for the rest of your life.',
    'The same job the rest of your life?',
    'I didnt know that.',
    'Whats the difference?'
    'Youll be happy to know that bees,'
    'as a species, havent had one day off'
    'in 27 million years.'
    'So youll just work us to death?',
    'Well sure try.',
    'Wow! That blew my mind!',
    "What's the difference?",
    'How can you say that?',
    'One job forever?',
    'Thats an insane choice to have to make.',
    'Im relieved. Now we only have',
    'to make one decision in life.',
    'But, Adam, how could they',
    'never have told us that?',
    'Why would you question anything?',
    'Were bees.',
    'Were the most perfectly',
    'functioning society on Earth.',
    'You ever think maybe things',
    'work a little too well here?',
    'Like what? Give me one example.',
    'I dont know. But you know',
    'what Im talking about.',
    'Please clear the gate.',
    'Royal Nectar Force on approach.',
    'Wait a second. Oheck it out.',
    '- Hey, those are Pollen Jocks!',
    '- Wow.',
    'Ive never seen them this close.',
    'They know what its like',
    'outside the hive.',
    'Yeah, but some dont come back.',
    '- Hey, Jocks!',
    '- Hi, Jocks!',
    'You guys did great!',
    'Youre monsters!',
    'Youre sky freaks! I love it! I love it!',
    '- I wonder where they were.',
    '- I dont know.',
    'Their days not planned.',
    'Outside the hive, flying who knows',
    'where, doing who knows what.',
    'You cantjust decide to be a Pollen',
    'Jock. You have to be bred for that.',
    'Right.',
    'Look. Thats more pollen',
    'than you and I will see in a lifetime.',
    'Its just a status symbol.',
    'Bees make too much of it.',
    'Perhaps. Unless youre wearing it',
    'and the ladies see you wearing it.',
    'Those ladies?',
    'Arent they our cousins too?',
    'Distant. Distant.',
    'Look at these two.',
    '- Oouple of Hive Harrys.',
    '- Lets have fun with them.',
    'It must be dangerous',
    'being a Pollen Jock.',
    'Yeah. Once a bear pinned me',
    'against a mushroom!',
    'He had a paw on my throat,',
    'and with the other, he was slapping me!',
    '- Oh, my!',]
spongebob_Script = ['I got it! I got it! I got it!',
'Dinghy ahoy.',
'Dinghy off the port bow.',
'Dinghy off the port bow! Dinghy off the port bow!',
'Dinghy off the port bow.',
'Captain, dinghy off the-- Dinghy.',
'I got it!',
'I got it.',
'Where is it?',
'Its right here, captain.',
'I never thought Id see it with me own eye.',
'Tickets to The SpongeBob Movie!',
'Who lives in a pineapple Under the sea?',
'Absorbent and yellow And porous is he SpongeBob SquarePants lf nautical nonsense Be something you wish SpongeBob SquarePants Then drop on the deck And flop like a fish SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants SpongeBob SquarePants',
'The sea. So mysterious, so beautiful. So...',
'...wet.',
'Our story begins in Bikini Bottoms popular undersea eatery The Krusty Krab restaurant, where--',
'- Back up. Back up. Hey. Wait a minute.',
'- What is happening? PIease, settIe down.',
'Weve got a situation in there Id rather not discuss tiII me manager gets here.',
'Look, there he is.',
'TaIk to me, Krabs.',
'It started out as a simpIe order: a Krabby Patty with cheese.',
'When the customer took a bite, no cheese!',
'Get ahoId of yourseIf, Eugene. Im going in.',
'Take it easy, friend. Im the manager of this estabIishment.',
'Everythings gonna be just fine.',
'Im reaIIy scared here, man. You got a name?',
'PhiI. You got a famiIy, PhiI?',
'Come on, PhiI, stay with me. Lets hear about that famiIy.',
'I got a wife and two beautifuI chiIdren.',
'Thats what its aII about. I want you to do me a favour, PhiI.',
'What?',
'Say cheese.',
'Order up.',
'Three cheers for the manager!',
'Hip! Hip!',
'Hip! Hip!',
'Hip! Hip!',
'Hooray!',
'Gary, I had that dream again.',
'And its finaIIy gonna come true. Today.',
'Sorry about this, caIendar.',
'Because today is the grand-opening ceremony for The Krusty Krab 2, where Mr. Krabs wiII announce the new manager.',
'Whos it gonna be, Gary?',
'WeII, Iets ask my waII of 37 4 consecutive empIoyee-of-the-month awards.',
'SpongeBob SquarePants.',
'Im ready. Promotion.',
'CIeanIiness is next to manager-Iiness.',
'Im ready. Promotion.',
'Im ready. Promotion.',
'SpongeBob! What are you doing in here?',
'I have to teII you something, Squidward.',
'Whatever it is, cant it wait untiI we get to work?',
'Theres no shower at work. What do you want?',
'I just wanted to say Ill be thanking you in my manageriaI acceptance speech today.',
'Get out!',
'Okay. Ill see you at the ceremony.',
'That sounds Iike the manager of the new Krusty Krab 2.',
'Oops. HoId on.',
'CongratuIations, buddy. Oh, thanks, Patrick.',
'And tonight, after my big promotion, were gonna party tiII were purpIe.',
'I Iove being purpIe!',
'Were going to the pIace where aII the action is.',
'You dont mean...? Oh, I mean.',
'Goofy Goobers Ice Cream Party Boat!',
'Oh, lm a Goofy Goober, yeah Youre a Goofy Goober, yeah Were all Goofy Goobers, yeah Goofy, goofy, goober, goober, yeah Id better get going.',
'Im ready. Promotion. Im ready. Promotion.',
'Good Iuck, SpongeBob. Hey, Iook for me at the ceremony.',
'I got a IittIe surprise for you. lm a Goofy Goober Yeah HeIIo, Bikini Bottom!',
'Perch Perkins here, coming to you Iive from in front of The Krusty Krab restaurant, for years the onIy pIace to get a deIicious and mouth-watering Krabby Patty. UntiI today, that is.',
'Thats right, foIks. Long-time owner Mr. Krabs is opening a new restaurant caIIed The Krusty Krab 2.',
'First of aII, congratuIations, Mr. Krabs.',
'HeIIo. I Iike money.',
'What inspired you to buiId a second Krusty Krab right next door to the originaI?',
'Money.',
'Curses!',
'Its not fair.',
'Krabs is being interviewed by Perch Perkins, and Ive never even had one customer!',
'Dont get worked up again, Plankton, l just mopped the floors.',
'Oh, Karen, my computer wife, if onIy I couId have managed to steaI the secret to Krabs success, the formuIa for the Krabby Patty.',
'Then peopIe wouId Iine up to eat at my restaurant.',
'Lord knows Ive tried.',
'Ive exhausted every eviI pIan in my fiIing cabinet...',
'- ...from A to Y. A to Y?',
'Yeah, A to Y. You know, the aIphabet.',
'What about Z?',
'- Z? Z. The letter after Y.',
'W, X, Y, Z. PIan Z!',
'- Here it is, just Iike you said. Oh, boy.',
'Its eviI.',
'Its diaboIicaI.',
'Its Iemon-scented.',
'This PIan Z cant possibIy faiI!',
'So enjoy today, Mr. Krabs, because by tomorrow, III have the formuIa.',
'Then everyone wiII eat at the Chum Bucket, and I wiII ruIe the worId!',
'AII haiI PIankton. AII haiI PIank--!',
'Im ready. Promotion. Im ready. Promotion.',
'I think I stepped in something.',
'Not in something, on someone, you twit.',
'Sorry, PIankton.',
'Are you on your way to the grand-opening ceremony?',
'No, I am not on my way over to the grand-opening ceremony.',
'Im busy pIanning to ruIe the worId!',
'WeII, good Iuck with that.',
'Im ready. Promotion. Im ready. Promotion.',
'Stupid kid.',
'WeIcome. WeIcome, everyone, to the grand opening of The Krusty Krab 2.',
'We paid $9 for this? I paid 1 0.',
'Now, before we begin with the ribbon-cutting, Id Iike to announce the name of our new manager.',
'Yay! Yeah!',
'Yeah! Now were taIking! Yeah!',
'Yes. WeII, anyway...',
'The new manager is a IoyaI, hard-working empIoyee.',
'Yes.',
'The obvious choice for the job.',
'Hes right.',
'A name you aII know. It starts with an S.',
'- Thats me. PIease weIcome our new manager...',
'...Squidward TentacIes.',
'Yes! Yeah!',
'Oh, better Iuck next time, buddy.',
'Yeah! AII right!',
'PeopIe of Bikini Bottom, as the manager of--',
'SpongeBob.',
'HoId the phone, foIks, Im getting an important news fIash from Mr. Krabs.',
'Go ahead, Mr. K.',
'Im making a compIete what of myseIf?',
'The most embarrassing thing youve ever seen?',
'And now its worse because Im repeating everything you say into the microphone?',
'Oh, for crying out Ioud, SpongeBob, you didnt get the job.',
'What? You did not get the job.',
'But-- But why?',
'SpongeBob, youre a great fry cook, but I gave the job to Squidward because being manager is a big responsibiIity.',
'WeII, Iets face it, hes more...',
'...mature than you. Im not...'
'...mature?',
'Lad, I mean this in the nicest of ways, but theres a word for what you are, and that word is...',
'Now, Iets see...',
'Dork? No, wait, thats not right. Not a dork.',
'A goofbaII? CIoser, but no, no, no.',
'A ding-a-Iing. Wing nut.',
'A KnuckIehead McSpazatron.',
'Okay, thats enough.',
'Look, what Im trying to say is, youre just a kid.',
'And to be a manager, you have to be a man.',
'Otherwise theyd caII it ''kid-ager.',
'You understand-ager? I mean, you understand?',
'I guess so, Mr. Krabs.',
'SpongeBob?',
'Im ready. Depression.',
'Im ready. Depression.',
'Poor kid.',]
poop = input('cobra or bee or sponge:')
poop.upper()
if poop == 'BEE':
    poop = bee_script
elif poop == 'COBRA':
    poop = episode_script
elif poop == 'SPONGE':
    poop = spongebob_Script
os.system('open -a Messages')
time.sleep(3)
i = int(0)
while i <= 182:
    keyboard = Controller()
    keyboard.type(poop[i])  
    keyboard.press(Key.enter)
    time.sleep(0.5)
    i += 1
    



