import os
import pynput
import time
from pynput.keyboard import Key, Controller
episode_script = [
    "All", "right,", "ladies", "and", "gentleman,",
    "this", "is", "the", "moment", "we've", "been", "waiting", "for.",
    "The", "presenta--",
    "Daniel", "LaRusso's", "gonna", "fight?",
    "Daniel", "LaRusso's", "gonna", "fight!",
    "Now,", "isn't", "this", "what", "it's", "all", "about,", "folks?",
    "Go!",
    "Hiyah!",
    "-Fight!",
    "-Here", "we", "go.",
    "Turn.", "Kneel.",
    "Johnny,", "you're", "a", "cream", "puff!",
    "Sweep", "the", "leg.",
    "You", "have", "a", "problem", "with", "that?",
    "No,", "Sensei.",
    "No", "mercy.",
    "Two", "points,", "LaRusso.", "Lawrence,", "nothing.",
    "Ready?", "Fight.",
    "One", "point,", "Lawrence.",
    "One", "point,", "Lawrence.", "Two,", "two.",
    "Hiyah!",
    "Get", "him", "a", "body", "bag!", "Yeah!",
    "Warning", "for", "illegal", "contact", "to", "the", "knee.",
    "Whoever", "wins", "the", "next", "point", "will", "be", "our", "new", "champion.",
    "Finish", "him!",
    "Daniel", "LaRusso!",
    "Ugh.",
    "Hey,", "I'm", "Miguel.",
    "My", "family", "and", "I", "just", "moved", "into", "109.",
    "Great.", "More", "immigrants.",
    "Actually,", "we're", "from", "Riverside.",
    "But", "anyways,", "I", "was", "just", "wondering", "if", "you", "were",
    "having", "trouble", "with", "your", "water", "pressure,",
    "'cause", "I", "know", "our", "sink's", "being", "a", "little", "weird", "right", "now", "and--",
    "Oh,", "bottles", "go", "in", "the", "blue", "bin.",
    "Listen,", "Menudo...",
    "I've", "lived", "in", "this", "sh*thole", "for", "over", "ten", "years.",
    "The", "pipe's", "don't", "work.", "The", "fountain's", "full", "of", "piss.",]
bee_script = [
    'According to all known laws of aviation',
    'there is no way a bee',
    'should be able to fly.',
    'Its wings are too small to get',
    'its fat little body off the ground.',
    'The bee, of course, flies anyway',
    'because bees dont care',
    'what humans think is impossible.',
    'Yellow, black. Yellow, black.',
    'Yellow, black. Yellow, black.',
    'Ooh, black and yellow!',
    'Lets shake it up a little.',
    'Barry! Breakfast is ready!',
    'Ooming!',
    'Hang on a second.',
    'Hello?',
    '- Barry?',
    '- Adam?',
    '- Oan you believe this is happening?',
    '- I cant. Ill pick you up.',
    'Looking sharp.',
    'Use the stairs. Your father',
    'paid good money for those.',
    'Sorry. Im excited.',
    'Heres the graduate.',
    'Were very proud of you, son.',
    'A perfect report card, all Bs.',
    'Very proud.',
    'Ma! I got a thing going here.',
    '- You got lint on your fuzz.',
    '- Ow! Thats me!',
    '- Wave to us! Well be in row 118,000.',
    '- Bye!',
    'Barry, I told you,',
    'stop flying in the house!',
    '- Hey, Adam.',
    '- Hey, Barry.',
    '- Is that fuzz gel?',
    '- A little. Special day, graduation.',
    'Never thought Id make it.',
    'Three days grade school,',
    'three days high school.',
    'Those were awkward.',
    'Three days college. Im glad I took',
    'a day and hitchhiked around the hive.',
    'You did come back different.',
    '- Hi, Barry.',
    '- Artie, growing a mustache? Looks good.',
    '- Hear about Frankie?',
    '- Yeah.',
    '- You going to the funeral?',
    '- No, Im not going.',
    'Everybody knows,',
    'sting someone, you die.',
    'Dont waste it on a squirrel.',
    'Such a hothead.',
    'I guess he could have',
    'just gotten out of the way.',
    'I love this incorporating',
    'an amusement park into our day.',
    'Thats why we dont need vacations.',
    'Boy, quite a bit of pomp...',
    'under the circumstances.',
    '- Well, Adam, today we are men.',
    '- We are!',
    '- Bee-men.',
    '- Amen!',
    'Hallelujah!',
    'Students, faculty, distinguished bees,',
    'please welcome Dean Buzzwell.',
    'Welcome, New Hive Oity',
    'graduating class of...',
    '...9:15.',
    'That concludes our ceremonies.',
    'And begins your career',
    'at Honex Industries!',
    'Will we pick ourjob today?',
    'I heard its just orientation.',
    'Heads up! Here we go.',
    'Keep your hands and antennas',
    'inside the tram at all times.',
    '- Wonder what itll be like?',
    '- A little scary.',
    'Welcome to Honex,',
    'a division of Honesco',
    'and a part of the Hexagon Group.',
    'This is it!',
    'Wow.',
    'Wow.',
    'We know that you, as a bee,',
    'have worked your whole life',
    'to get to the point where you',
    'can work for your whole life.',
    'Honey begins when our valiant Pollen',
    'Jocks bring the nectar to the hive.',
    'Our top-secret formula',
    'is automatically color-corrected,',
    'scent-adjusted and bubble-contoured',
    'into this soothing sweet syrup',
    'with its distinctive',
    'golden glow you know as...',
    'Honey!',
    '- That girl was hot.',
    '- Shes my cousin!',
    '- She is?',
    '- Yes, were all cousins.',
    '- Right. Youre right.',
    '- At Honex, we constantly strive',
    'to improve every aspect',
    'of bee existence.',
    'These bees are stress-testing',
    'a new helmet technology.',
    '- What do you think he makes?',
    '- Not enough.',
    'Here we have our latest advancement,',
    'the Krelman.',
    '- What does that do?',
    '- Oatches that little strand of honey',
    'that hangs after you pour it.',
    'Saves us millions.',
    'Oan anyone work on the Krelman?',
    'Of course. Most bee jobs are',
    'small ones. But bees know',
    'that every small job,',
    'if its done well, means a lot.',
    'But choose carefully',
    'because youll stay in the job',
    'you pick for the rest of your life.',
    'The same job the rest of your life?',
    'I didnt know that.',
    'Whats the difference?'
    'Youll be happy to know that bees,'
    'as a species, havent had one day off'
    'in 27 million years.'
    'So youll just work us to death?',
    'Well sure try.',
    'Wow! That blew my mind!',
    "What's the difference?",
    'How can you say that?',
    'One job forever?',
    'Thats an insane choice to have to make.',
    'Im relieved. Now we only have',
    'to make one decision in life.',
    'But, Adam, how could they',
    'never have told us that?',
    'Why would you question anything?',
    'Were bees.',
    'Were the most perfectly',
    'functioning society on Earth.',
    'You ever think maybe things',
    'work a little too well here?',
    'Like what? Give me one example.',
    'I dont know. But you know',
    'what Im talking about.',
    'Please clear the gate.',
    'Royal Nectar Force on approach.',
    'Wait a second. Oheck it out.',
    '- Hey, those are Pollen Jocks!',
    '- Wow.',
    'Ive never seen them this close.',
    'They know what its like',
    'outside the hive.',
    'Yeah, but some dont come back.',
    '- Hey, Jocks!',
    '- Hi, Jocks!',
    'You guys did great!',
    'Youre monsters!',
    'Youre sky freaks! I love it! I love it!',
    '- I wonder where they were.',
    '- I dont know.',
    'Their days not planned.',
    'Outside the hive, flying who knows',
    'where, doing who knows what.',
    'You cantjust decide to be a Pollen',
    'Jock. You have to be bred for that.',
    'Right.',
    'Look. Thats more pollen',
    'than you and I will see in a lifetime.',
    'Its just a status symbol.',
    'Bees make too much of it.',
    'Perhaps. Unless youre wearing it',
    'and the ladies see you wearing it.',
    'Those ladies?',
    'Arent they our cousins too?',
    'Distant. Distant.',
    'Look at these two.',
    '- Oouple of Hive Harrys.',
    '- Lets have fun with them.',
    'It must be dangerous',
    'being a Pollen Jock.',
    'Yeah. Once a bear pinned me',
    'against a mushroom!',
    'He had a paw on my throat,',
    'and with the other, he was slapping me!',
    '- Oh, my!',]
poop = input('cobra or bee:')
poop.upper()
if poop == 'BEE':
    poop = bee_script
elif poop == 'COBRA':
    poop = episode_script
os.system('open -a Messages')
time.sleep(3)
i = int(0)
while i <= 182:
    keyboard = Controller()
    keyboard.type(poop[i])  
    keyboard.press(Key.enter)
    time.sleep(0.5)
    i += 1
    

